#!/usr/bin/env node
'use strict';
/**
 * Extracts 3 SVG icons from npm packages and writes assets/js/icons.js.
 *
 * Sources:
 *   - WhatsApp / Messenger : simple-icons  (filled brand paths, fill="currentColor")
 *   - Email                : lucide-static (stroke="currentColor", outline)
 *
 * Run via `npm run build` or standalone:
 *   node scripts/extract-icons.cjs
 */
const fs   = require('fs');
const path = require('path');

const NM  = path.join(__dirname, '..', 'node_modules');
const OUT = path.join(__dirname, '..', 'assets', 'js', 'icons.js');

const SIZE = 22;

function readFile(relPath) {
  const abs = path.join(NM, relPath);
  if (!fs.existsSync(abs)) throw new Error(`Icon file not found: ${abs}`);
  return fs.readFileSync(abs, 'utf8');
}

function simpleSvg(name) {
  const raw = readFile(`simple-icons/icons/${name}.svg`);
  return raw
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<title>[^<]*<\/title>/g, '')
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim()
    // Normalise the opening <svg …> tag: strip role/xmlns, set size + currentColor fill
    .replace(
      /<svg[^>]*>/,
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${SIZE}" height="${SIZE}" fill="currentColor" aria-hidden="true">`,
    );
}

function lucideSvg(name) {
  const raw = readFile(`lucide-static/icons/${name}.svg`);
  return raw
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim()
    .replace(
      /<svg[^>]*>/,
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${SIZE}" height="${SIZE}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">`,
    );
}

const icons = {
  whatsapp:  simpleSvg('whatsapp'),
  messenger: simpleSvg('messenger'),
  email:     lucideSvg('mail'),
};

const content = [
  '/* Auto-generated by scripts/extract-icons.cjs — do not edit directly */',
  `window.TBC_ICONS = ${JSON.stringify(icons, null, 2)};`,
  '',
].join('\n');

fs.writeFileSync(OUT, content, 'utf8');
console.log(`✓  Icons extracted → assets/js/icons.js`);
